### ISSUE TITLE
Please add git tag for release v0.0.9

### ISSUE THREAD

**Issue by jaredbeck** [begriffs/clean_pagination#5]
I'm trying to determine if I can upgrade from 0.0.8 to 0.0.9 and a git tag would make it easier to compare.  Thanks!

**Comment by jaredbeck** [comment]
And then I compared with master and there were only two commits, lol.

https://github.com/begriffs/clean_pagination/compare/v0.0.8...master

Still, a tag for every release is appreciated.

**Comment by begriffs** [comment]
Oops, I had the version bump commit and tags locally but forgot to push them to github. There you go, sorry for the delay!
