### ISSUE TITLE
How to let "normal" clients download a paged resource completely?

### ISSUE THREAD

**Issue by dnauck** [begriffs/clean_pagination#6]
Is it possible to let normal clients (like Chrome, Firefox, IE) to download a paged resource?

In my [.NET implementation](https://github.com/begriffs/angular-paginate-anything/wiki/How-to-configure-.NET) if also a hard limit of the max page size like your ruby gem.
E.g. the max page size is 1000 but we have 170000 items in the resource.

But when a normal browser access the resource it is not able to download the complete resource, only the max page size.

Any ideas on how to fix this or work around?

**Comment by begriffs** [comment]
In the Ruby gem you could pass in `Float::INFINITY` for the `max_range_size` argument of `paginate`. Maybe you could modify the .NET to accept a similar thing.

Then you'll want to be careful that you don't accidentally request all the items in your front end code, but it will remove the download limit.

**Comment by begriffs** [comment]
I'm going to close this issue. Feel free to reopen it if you have not solved the problem.
